# Generated by Django 5.1.6 on 2025-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('criminal', 'Criminal'), ('civil', 'Civil'), ('family', 'Family'), ('labor', 'Labor')], default='criminal', max_length=20),
        ),
    ]
