# Generated by Django 5.1.4 on 2025-03-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='cases_taken',
            new_name='cases_active',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='cases_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='wiki_contributions',
            field=models.IntegerField(default=0),
        ),
    ]
